name: "Attach Release Artifacts"

on:
  release:
    types: [published]

jobs:
  attach-release-artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v5
        with:
          commit: ${{GITHUB_SHA}}
          name: RealAntennas

      - name: Upload package to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./RealAntennas.zip
          asset_name: RealSolarSystem_${{ github.event.release.tag_name }}.zip
          asset_content_type: application/zip
